"""Add is_live field to Content model

Revision ID: 05ef36021af3
Revises: 154a78f5d6e1
Create Date: 2025-04-17 19:32:40.429961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ef36021af3'
down_revision = '154a78f5d6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_live', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('is_live')

    # ### end Alembic commands ###
