"""Add date_modified to Content model

Revision ID: 65835df6c7f3
Revises: 
Create Date: 2025-01-17 11:46:08.772676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65835df6c7f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
