"""Add timestamps to Content model

Revision ID: 751b80dc5260
Revises: 65835df6c7f3
Create Date: 2025-01-23 12:53:56.787418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751b80dc5260'
down_revision = '65835df6c7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [column['name'] for column in inspector.get_columns('content')]
    
    with op.batch_alter_table('content', schema=None) as batch_op:
        if 'created_at' not in columns:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        if 'modified_at' not in columns:
            batch_op.add_column(sa.Column('modified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
